### ISSUE TITLE
Dialog Error

### ISSUE THREAD

**Issue by SaniokUA** [toshikurauchi/MaskedEditText#25]
When i want create a new dialog I have this error:

```
  Dialog alert = new Dialog(this);
  View view = (LinearLayout) getLayoutInflater().inflate(R.layout.add_phone_number, null);
```

`10-11 14:33:36.850 22666-22666/com.onsoft.alarmcall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.onsoft.alarmcall, PID: 22666
                                                                      android.view.InflateException: Binary XML file line #37: Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                          at com.onsoft.alarmcall.MainActivity.showAddNumberDialog(MainActivity.java:125)
                                                                          at com.onsoft.alarmcall.MainActivity.access$000(MainActivity.java:28)
                                                                          at com.onsoft.alarmcall.MainActivity$1.onClick(MainActivity.java:67)
                                                                          at android.view.View.performClick(View.java:4469)
                                                                          at android.view.View$PerformClick.run(View.java:18788)
                                                                          at android.os.Handler.handleCallback(Handler.java:808)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                          at com.onsoft.alarmcall.MainActivity.showAddNumberDialog(MainActivity.java:125) 
                                                                          at com.onsoft.alarmcall.MainActivity.access$000(MainActivity.java:28) 
                                                                          at com.onsoft.alarmcall.MainActivity$1.onClick(MainActivity.java:67) 
                                                                          at android.view.View.performClick(View.java:4469) 
                                                                          at android.view.View$PerformClick.run(View.java:18788) 
                                                                          at android.os.Handler.handleCallback(Handler.java:808) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5349) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.NullPointerException
                                                                          at br.com.sapereaude.maskedEditText.MaskedEditText.generatePositionArrays(MaskedEditText.java:205)
                                                                          at br.com.sapereaude.maskedEditText.MaskedEditText.cleanUp(MaskedEditText.java:122)
                                                                          at br.com.sapereaude.maskedEditText.MaskedEditText.<init>(MaskedEditText.java:69)
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                          at com.onsoft.alarmcall.MainActivity.showAddNumberDialog(MainActivity.java:125) 
                                                                          at com.onsoft.alarmcall.MainActivity.access$000(MainActivity.java:28) 
                                                                          at com.onsoft.alarmcall.MainActivity$1.onClick(MainActivity.java:67) 
                                                                          at android.view.View.performClick(View.java:4469) 
                                                                          at android.view.View$PerformClick.run(View.java:18788) 
                                                                          at android.os.Handler.handleCallback(Handler.java:808) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5349) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
 `

**Comment by SaniokUA** [comment]
http://prntscr.com/gw1b9w  this way not works :)
